- hosts: localhost
  become: yes
  connection: local
  
  tasks:
    - name: Clean old docker version
      ansible.builtin.package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
    
    - name: update
      community.general.pacman:
        update_cache: yes
        upgrade: true

    - name: Install required packages
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    
    - name: Add GPG key
      community.general.pacman_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
        keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"
        id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA

    - name: Debug
      ansible.builtin.debug:
        msg: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release }} stable"

    - name: Register new repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install docker compose
      ansible.builtin.pip:
        name: docker-compose
        state: present
        
